set NET_FRAMEWORK_CSC=C:\Program Files (x86)\MSBuild\14.0\Bin\
set Need_Define=UNITY_5_2_1;UNITY_5_2;UNITY_5;ENABLE_NEW_BUGREPORTER;ENABLE_2D_PHYSICS;ENABLE_4_6_FEATURES;ENABLE_AUDIO;ENABLE_CACHING;ENABLE_CLOTH;ENABLE_FRAME_DEBUGGER;ENABLE_GENERICS;ENABLE_HOME_SCREEN;ENABLE_IMAGEEFFECTS;ENABLE_LIGHT_PROBES_LEGACY;ENABLE_MICROPHONE;ENABLE_MULTIPLE_DISPLAYS;ENABLE_PHYSICS;ENABLE_PLUGIN_INSPECTOR;ENABLE_SHADOWS;ENABLE_SINGLE_INSTANCE_BUILD_SETTING;ENABLE_SPRITES;ENABLE_TERRAIN;ENABLE_RAKNET;ENABLE_UNET;ENABLE_UNITYEVENTS;ENABLE_VR;ENABLE_WEBCAM;ENABLE_WWW;ENABLE_CLOUD_SERVICES;ENABLE_CLOUD_SERVICES_ADS;ENABLE_CLOUD_HUB;ENABLE_CLOUD_PROJECT_ID;ENABLE_CLOUD_SERVICES_ANALYTICS;ENABLE_CLOUD_SERVICES_UNET;ENABLE_CLOUD_SERVICES_BUILD;ENABLE_CLOUD_LICENSE;ENABLE_EDITOR_METRICS;ENABLE_REFLECTION_BUFFERS;INCLUDE_DYNAMIC_GI;INCLUDE_GI;INCLUDE_IL2CPP;INCLUDE_DIRECTX12;PLATFORM_SUPPORTS_MONO;RENDER_SOFTWARE_CURSOR;ENABLE_LOCALIZATION;ENABLE_ANDROID_ATLAS_ETC1_COMPRESSION;UNITY_ANDROID;UNITY_ANDROID_API;ENABLE_SUBSTANCE;UNITY_ANDROID_API;ENABLE_TEXTUREID_MAP;ENABLE_EGL;ENABLE_NETWORK;ENABLE_RUNTIME_GI;ENABLE_CRUNCH_TEXTURE_COMPRESSION;ENABLE_UNITYADS_RUNTIME;UNITY_UNITYADS_API;ENABLE_MONO;ENABLE_PROFILER;UNITY_ASSERTIONS;UNITY_EDITOR;UNITY_EDITOR_64;UNITY_EDITOR_WIN;UNITY_TEAM_LICENSE;UNITY_PRO_LICENSE;CROSS_PLATFORM_INPUT;MOBILE_INPUT

set Need_dll_1=F:\Unity\Unity\Editor\Data\Managed\UnityEngine.dll
set Need_dll_2=F:\Unity\Unity\Editor\Data\Managed\UnityEditor.dll
set Need_dll_3=F:\Unity\Unity\Editor\Data\UnityExtensions\Unity\GUISystem\UnityEngine.UI.dll
set Need_dll_4=F:\2018_Game\Game\Project\Assets\Scripts\dlls\protobuf\protobuf-net.dll
set Need_dll_5=F:\2018_Game\Game\Project\Assets\Scripts\dlls\protobuf\GameProtocols.dll
set Need_dll_6=F:\2018_Game\Game\Project\Assets\Scripts\dlls\protobuf\GameProtocolsData.dll

set CS_FILE=F:\2018_Game\Game\Project\Assets
set Out_DLL=F:\2018_Game\Game\Project\Assets\bat\Unity.dll

C:
cd %NET_FRAMEWORK_CSC%  
csc.exe /t:library /define:%Need_Define% /r:%Need_dll_1%;%Need_dll_2%;%Need_dll_3%;%Need_dll_4%;%Need_dll_5%;%Need_dll_6% /out:%Out_DLL% /recurse:%CS_FILE%\*.cs 

pause